spring:
  application:
    name: shop
  datasource:
    url: jdbc:h2:mem:shopdatabase
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health,info,metrics, prometheus
  health:
    mail:
      enabled: false
    db:
      enabled: true
